### ISSUE TITLE
LF error for PHP 7 provision file

### ISSUE THREAD

**Issue by linuxbastard** [wpengine/hgv#256]
`==> hgv: TASK: [php-fpm | Compile php7 memcached] **************************************
==> hgv: failed: [127.0.0.1] => {"cmd": "/vagrant/provisioning/roles/php-fpm/files/build-php7-memcached.sh", "
failed": true, "rc": 2}
==> hgv: msg: [Errno 2] No such file or directory
==> hgv:
==> hgv: FATAL: all hosts have already failed -- aborting
==> hgv:
==> hgv: PLAY RECAP ********************************************************************
==> hgv:            to retry, use: --limit @/root/playbook.retry
==> hgv: 127.0.0.1                  : ok=44   changed=40   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

running dos2unix on VM fixes it.

Windows 10
VirtualBox 5.0.4
Vagrant 1.7.4

**Comment by ericmann** [comment]
Thanks for the report. We'll get this fixed with the next release.

**Comment by dupski** [comment]
Hi Guys. Sadly we still have this issue on windows with the current codebase. We are using an older version of git (v1.9.5), which could be the cause.

Could the 4 lines in that shell script not be moved into an ansible 'shell' task? I'll give this a try when I next do a build.

**Comment by brendonlamb** [comment]
Any progress with this? Any workaround?

```
==> hgv: TASK [php-fpm : Compile php7 memcached] *******************************
*********
==> hgv: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/vagrant/prov
isioning/roles/php-fpm/files/build-php7-memcached.sh", "failed": true, "msg": "[
Errno 2] No such file or directory", "rc": 2}
==> hgv:
==> hgv: NO MORE HOSTS LEFT ****************************************************
*********
==> hgv:        to retry, use: --limit @/vagrant/provisioning/playbook.retry
==> hgv:
==> hgv: PLAY RECAP ************************************************************
*********
==> hgv: 127.0.0.1                  : ok=38   changed=1    unreachable=0    fail
ed=1
```


Windows 10
VirtualBox 5.1.4
Vagrant 1.8.5
Git 2.10.0

**Comment by TmpR** [comment]
Any idea when this will be fixed? Same php7 LF issues on Win10, tried converting php7 provision scripts to Unix EOL but still won't provision.

**Comment by ehoanshelt** [comment]
@TmpR Can you try testing this again with the latest master branch? Please let me know if you are experiencing the same issue!
